kind: Service
apiVersion: v1
metadata:
  name: flaskapp-service
spec:
  type: NodePort
  selector:
    app: flask_app
  ports:
  - protocol: TCP
    port: 32200
    nodePort: 32200

---

apiVersion: v1
kind: Pod
metadata:
  name: flaskapp
  labels:
    app: flask_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask_app
  template:
    metadata:
      labels:
        app: flask_app
    spec:
      containers:
      - name: flask_app
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 32200
