kind: Service
apiVersion: v1
metadata:
  name: flaskapp-service
spec:
  type: NodePort
  selector:
    app: flask_app
  ports:
  - protocol: TCP
    port: 32200
    nodePort: 32200

---

apiVersion: v1
kind: Pod
metadata:
  name: flaskapp
  labels:
    app: flask_app
spec:
  containers:
  - name: flask_app
    image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
    ports:
    - name: flask-port
      containerPort: 32200
